### ISSUE TITLE
Request Bypass timer

### ISSUE THREAD

**Issue by falfan2018** [hellshltd/Universal-Bypass#12]
Example link : 
https://simaholina.xyz/8-auto-insurance-myths/?url=aHR0cDovL2xpbmtzaHJpbmsubmV0LzdFd0JZQQ==
http://www.losstor.com/ini/?site=aHR0cDovL2thcnVuZy5pbi9HeXVjYw==&c=0&user=1
http://bagisoft.net/?site=aHR0cDovL2FkZi5seS9zRjJOdA==&c=0&user=
https://skinnycat.net/ulasan-rincian-bukti-pembayaran-ad-network-adcash/?d=aHR0cHM6Ly91c2Vyc2Nsb3VkLmNvbS90bTNuNjVjdW43Y2g=#breadcrumbs
https://one-piece-x.com.br/download/?23515

Thanks

**Comment by timmyrs** [comment]
Bypasses for all sites have been added in 3.1 which I will release soon. Thanks for your help!
