### ISSUE TITLE
Bypass timer req

### ISSUE THREAD

**Issue by alvahn** [hellshltd/Universal-Bypass#14]
Filehosting : https://www.extmatrix.com/files/EEJ11HYC/70114Kouhaku-720p.part10.rar.html

shortener : http://earn-url.com/UAv3LlZE

https://ar.akoam.net/download/73b628e99f36/Game-of-Thrones-S05E01-HDTV-akoam-com-mkv

http://1v.to/t/VjFaV2IxVXdNVWhVYTFacFRURndUbFJYTVRObFZtdDNXa1ZrYkdKV1NrbFdiR2hYVjJzeGNXSkVRbFZTUlRWaFdrZDRTMU5XU2xWUmJXeFhWa1ZhVmxaR1ZtdFhiRUpTVUZRd1BRPT0rUA==

https://dwindly.io/7QC2=example.com/

http://8maple.ru/249740/

http://js.fakirdebrid.net/advertisement/AD1.php?id=xxxxxxx

http://vpsat.net/i.php?c=687474703a2f2f6164626c6f636b706c75732e6f72672f

Thank you so much.

**Comment by timmyrs** [comment]
Bypasses for some sites have been added in 3.2 which I will release soon.
I did not add a bypass for 8maple.ru because that's just a DDOS protection and not an actual timer.
Thanks for your help, anyway!
