### ISSUE TITLE
Request bypass timer

### ISSUE THREAD

**Issue by RaveN0X87** [hellshltd/Universal-Bypass#17]
Example link : http://shrinkearn.com/AlKe
https://short2win.com/l3twmN
http://earnbig.ca/DYnB
http://cutearn.ca/CAtetx
http://earn-url.com/UAv3LlZE
http://clik.pw/a5CJg
http://shortit.ca/x5la
http://oturl.com/W0J35tMY

**Comment by timmyrs** [comment]
Most of them are already bypassed. Please check your links before submitting them.
