### ISSUE TITLE
Request kurosafe new domain

### ISSUE THREAD

**Issue by RaveN0X87** [hellshltd/Universal-Bypass#33]
Example link : https://binerfile.info/?site=aHR0cHM6Ly9kcml2ZS5rdXJvZ2F6ZS5wdy9maWxlL3ZiU2FQbGo5dHREVlQxdWFyNGp3&c=0&user=

https://pafpaf.info/?site=aHR0cHM6Ly9kcml2ZS5rdXJvZ2F6ZS5wdy9maWxlL3ZiU2FQbGo5dHREVlQxdWFyNGp3

**Comment by timmyrs** [comment]
Thanks for noticing. Fixed in 4.2.
