### ISSUE TITLE
Bug https://hightech.web.id/

### ISSUE THREAD

**Issue by RaveN0X87** [hellshltd/Universal-Bypass#41]
the notification say skipped but didn't skipped 
example link : 
https://hightech.web.id/ko82jkl9/index.php?site=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MWxCVTlCY2ZvUDJSZVdmdmJDUG9RUWc2N0lVT2ltcUJS#generate

**Comment by timmyrs** [comment]
These websites are getting weirder but I fixed it in 4.3. Thanks for the report.
