### ISSUE TITLE
this shortener stuck

### ISSUE THREAD

**Issue by sindysenora** [hellshltd/Universal-Bypass#42]
https://menantisenja.com/?id=aHR0cHM6Ly9kcml2ZS5rdXJvZ2F6ZS5wdy9maWxlL2dwUW1yc0ZBaHVkejBjOVN5bVpJ
Disabling this extension helps.

**Comment by timmyrs** [comment]
For me, the website is broken in Firefox and Chrome regardless of extensions.

**Comment by sindysenora** [comment]
okay  btw thanks for your bypasser project
