### ISSUE TITLE
redirect to wrong destination 

### ISSUE THREAD

**Issue by alvahn** [hellshltd/Universal-Bypass#47]
Example : http://jojosrew.site/?r=aHR0cDovL2N1dHVybC5wdy8/aWQ9UVhrcmJVODFjSHBSWm5CRFRVWkZSamR6UkRaQ0szSm5Oa3czU0U1UFkxRkpNREpVWW1KQlEybFZURGcyYWtscGJYUTVTVTQ1V1ZnemQzSm1UMGQxUkE9PQ==

http://jojosrew.site/?r=aHR0cDovL2N1dHVybC5wdy8/aWQ9VjNRM2JHbHpWRnBDVEZCUmFWbE5SamhFZG1kNGVHTmxWRFZ5Vmtrck1rRmljRkZQV1dzNWFHODBaV3huV1c0elRsZFJaREJ5VXk5bVZFWnJSbk5LVkE9PQ==

agancloud.site/?r=aHR0cDovL2pvam9zcmV3LnNpdGUvP3I9YUhSMGNEb3ZMMk4xZEhWeWJDNXdkeTgvYVdROVpETk9UVlZYYkVaVVJVWlJWbGRTYWt4NmFFdFhha2w0Vm10YWMySkdaSGRTVjNoV1lYazVSbFpZWkd4bGJFazBVMGhXYUdKcldrUlhWRTV6WlVWT1VFc3diREZUTUZVMVpGZFNhMUZwZERSV1ZURnlUbXRXZDB4NlNuRmFNRTVXVmpOd1UySllWWEpUVjJ4UllURm5NMlF5VFRST1IzUnBaVlphYVZaNlJsQlpNRkpUVWxkb2NHRldVVEpoYlRnNQ==

**Comment by timmyrs** [comment]
Gives me the same destination with and without Universal Bypass. Make sure you're using the latest version.
