### ISSUE TITLE
Request idnation.net

### ISSUE THREAD

**Issue by alvahn** [hellshltd/Universal-Bypass#48]
Example link : https://idnation.net/movie-koe-no-katachi-dub-inggris-tayang-2-februari/?page=N1g3bnNHTmVmdG5xUlR0cmpWTVlIdXhxM0s4cmMrRXIycXBHdWh3ZzhaQzVML3RMK29Xb2NETUJJTTlhSmh6V1dtYWtlc0haeHZ6N0JTUG8rYVZQRXB6eE1HSEMyeC9OWFVVQ2hMZEJacEE9

**Comment by timmyrs** [comment]
Sorry, the site has no timer and I won't make Universal Bypass click a button because that could lead to all sort of madness.
