### ISSUE TITLE
idsly.bid not working after update 

### ISSUE THREAD

**Issue by RaveN0X87** [hellshltd/Universal-Bypass#51]
before update i use v4.5 still working perfectly and can bypass and now after i update to v4.5.1 didn't work anymore 
Example : https://idsly.bid/4Nxl
https://idsly.bid/FFu1X
https://idsly.bid/vE2EQqH3

please fix it
thank you so much

**Comment by timmyrs** [comment]
Sorry, it seems they switched to AdLinkFly which has backend validation.

**Comment by RaveN0X87** [comment]
@timmyrs but if i used old version still working

**Comment by timmyrs** [comment]
I had removed the bypass in 4.5.1 because it broke the site but if it worked for you, you can create custom bypass with the old code: https://github.com/hellshltd/Universal-Bypass/blob/37222ef0d8ca9f2310c27e3f43b92ef98e0fd5d6/content_script.js#L662-L683

**Comment by RaveN0X87** [comment]
@timmyrs ok thanks

**Comment by timmyrs** [comment]
You click on the Universal Bypass icon in your browser, you click on "Options." There, you click "Add" under "Custom Bypasses." A new custom bypass has been created called "Untitled Bypass" and it will execute for example.com and example.org — rename the bypass to "idsly.bid Bypass" and use "idsly.bid" as domain. Finally, paste the code and click "Save." Once saved, the bypass will run on all specified domains (idsly.bid).

**Comment by RaveN0X87** [comment]
@timmyrs i try and didn't work for me not like if i use v.45 universal bypass

**Comment by timmyrs** [comment]
Probably because of the functions which are not available with custom bypasses. Anyway, I don't think the bypass will do anything for you because as I said they use backend validation now.
