### ISSUE TITLE
Conflict with Nano Defender

### ISSUE THREAD

**Issue by fireattack** [hellshltd/Universal-Bypass#61]
Chrome 68 on Windows 7

STR:

1. Install [Nano Defender](https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb) (technically you need to have either Nano Adblocker or UBlock Origin for it to actually work, but it alone is enough to cause conflict).
1. Install UB.
1. Open http://bangumi.tv/

Depending on which extension is enabled first, the console will either throw

```
VM464:61 [Nano] Failed :: Adfly Bypasser
(anonymous) @ VM464:61
(anonymous) @ VM464:63
a.inject @ core.js:246
a.generic.Adfly @ core.js:1404
(anonymous) @ rules-common.js:79
VM466:33 Uncaught TypeError: Cannot read property 'error' of undefined
    at <anonymous>:33:27
    at <anonymous>:35:7
```
from Nano defender, or

```
VM881:101 Uncaught TypeError: Cannot redefine property: ysmm
    at defineProperty (<anonymous>)
    at <anonymous>:101:3
    at <anonymous>:840:4
```
from UB.

**Comment by timmyrs** [comment]
Generally, Universal Bypass should be faster. However, since Nano Defender also has an Adfly Bypasser, I trust that it will be bypassed regardless. Obviously, this doesn't break either extension.

**Comment by jspenguin2017** [comment]
> Generally, Universal Bypass should be faster. 

If you mean inject order, then that's simply not true, the order of content script injection is purely determined by install order and nothing else. 

If you mean the time it takes for your code to execute, then sure, your script is shorter. 

> Obviously, this doesn't break either extension.

If ND ran first, it would breaks yours. You should try-catch all your `Object.defineProperty`.

**Comment by timmyrs** [comment]
I'm pretty confident in the way Universal Bypass injects itself into the websites and it certainly beats uBlockOrigin which is enough to avoid major problems. Of course, since you have your little Nano Defender which does a bit more than what it's supposed to do, I've wrapped all calls with a try-catch in 5.5.5.2.

**Comment by jspenguin2017** [comment]
uBO scriptlets are not content scripts, so they are injected later. 

ND always had timer boosting and URL-shortener bypassing mechanism, since 2016.

**Comment by jspenguin2017** [comment]
uBO scriptlets are not content scripts, so they are injected later. 

ND always had timer boosting and URL-shortener bypassing mechanism, since early 2017, a few months after the project started. Most of the timer boosting are now handled by uBO these days though.

**Comment by timmyrs** [comment]
I also think it's a bit weird for uBO to do that but as long as Universal Bypass loads faster and uBO doesn't interfere that's alright.

**Comment by jspenguin2017** [comment]
It's not weird, ads timers are a form of ads.

**Comment by timmyrs** [comment]
I guess so.
